.etnaviv-test:arm32:
  extends:
    - .baremetal-test-arm32
    - .etnaviv-rules
  script:
    - ./install/bare-metal/fastboot.sh
  variables:
    BM_CMDLINE: "ip=dhcp console=ttymxc0,115200n8 root=/dev/nfs rw nfsrootdebug init=/init $BM_KERNELARGS"
    BM_KERNEL: /baremetal-files/zImage
    FLAKES_CHANNEL: "#etnaviv-ci"

.etnaviv-test:arm64:
  extends:
    - .baremetal-test-arm64
    - .etnaviv-rules
  script:
    - ./install/bare-metal/fastboot.sh
  variables:
    BM_CMDLINE: "ip=dhcp console=ttymxc0,115200n8 root=/dev/nfs rw nfsrootdebug init=/init $BM_KERNELARGS"
    BM_KERNEL: /baremetal-files/Image
    FLAKES_CHANNEL: "#etnaviv-ci"

.etnaviv-gc2000:arm32:
  extends:
    - .etnaviv-test:arm32
  variables:
    BM_DTB: /baremetal-files/imx6q-cubox-i.dtb
    DEQP_EXPECTED_RENDERER: GC2000
    GPU_VERSION: "etnaviv-gc2000"
  tags:
    - etnaviv-gc2000

.etnaviv-gc7000:arm64:
  extends:
    - .etnaviv-test:arm64
  variables:
    BM_DTB: /baremetal-files/imx8mq-nitrogen.dtb
    DEQP_EXPECTED_RENDERER: GC7000
    GPU_VERSION: "etnaviv-gc7000"
  tags:
    - austriancoder-etnaviv-imx8mq-nitrogen

gc2000_gles2:
  extends:
    - .etnaviv-gc2000:arm32
    - .etnaviv-manual-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2

gc2000_gles2_asan:
  extends:
    - gc2000_gles2
    - .baremetal-arm32-asan-test
  variables:
    DEQP_FRACTION: 100
    FDO_CI_CONCURRENT: 1

gc2000_piglit:
  extends:
    - .piglit-test
    - .etnaviv-gc2000:arm32
    - .etnaviv-manual-rules
  variables:
    PIGLIT_PLATFORM: gbm
    PIGLIT_PROFILES: gpu
    TEST_PHASE_TIMEOUT: 40

gc7000_gles2:
  extends:
    - .etnaviv-gc7000:arm64
    - .etnaviv-manual-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2
